### ISSUE TITLE
Installation works not

### ISSUE THREAD

**Issue by JulianBorghuis** [JoCat/JCat-Radio-CMS#8]
Hello,
The Installation works not,
I see no text,
Have tried https and http
Error logs says that there much functions are not defined
Php versions tried
What now

**Comment by JoCat** [comment]
If you can wait 1-2 day, i upload new fix version

This code old and bad ))

**Comment by JulianBorghuis** [comment]
mhh oke i have no choise my hope was that you can resolve this now :(
