### ISSUE TITLE
Есть инструкция как запустить?

### ISSUE THREAD

**Issue by be2clack** [JoCat/JCat-Radio-CMS#9]
Есть инструкция как запустить?

**Comment by JoCat** [comment]
Не, на старых версиях был скрипт установки, но сейчас я бы не советовал их использовать

**Comment by JoCat** [comment]
Ну а вообще, если интересно можете скачать файлы, закинуть на веб сервер, залить дамп базы данных из `jrc_db.sql` и потыкать движок))
Конфиги лежат в `/engine/data/`

С dev версией движка немного по другому:
Скачать файлы, если отсутствует composer - установить (https://getcomposer.org/download/)
После установки прописать `php composer install` в папке с движком
Также нужен дамп бд, если что могу скинуть, нужно залит его и настроить движок на работу с бд в `/backend/configs/main.php` и `/frontend/configs/main.php` значение `connect`

**Comment by be2clack** [comment]
`Notice: Trying to get property of non-object in /engine/classes/db_connect.php on line 14

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Нет такого файла или каталога' in /engine/classes/db_connect.php:20 Stack trace: #0 /engine/classes/db_connect.php(20): PDO->__construct('mysql:host=;dbn...', NULL, NULL, Array) #1 /engine/classes/stats.php(3): require_once('/home/users/k/k...') #2 /engine/engine.php(22): include('/home/users/k/k...') #3 /index.php(27): require_once('/home/users/k/k...') #4 {main} thrown in /engine/classes/db_connect.php on line 20`

такая фигня у меня ))

**Comment by JoCat** [comment]
в `engine/data` есть файл `db_config.json`?

**Comment by be2clack** [comment]
> в `engine/data` есть файл `db_config.json`?

да есть там все настроил, бд загрузил

**Comment by JoCat** [comment]
Должно работать, проверяйте доступы к бд либо права на чтение файлов
